export interface Query{
    nome?:string,
    classe?:string,
    action?:string,
    concentration?: boolean | string,
    ritual?: boolean | string,
    level?: number | string,
    school?: string,
    source?: string,
    type?: string,
    cr?: string,
    image?: boolean | string,
    desc?: string,
    rarity?: string,
    requiresAttunement?: boolean | string,
}